#!/bin/sh

# launch fcgi server
# run as root so we can read repositories regardless
# let nginx own socket so we can talk
spawn-fcgi -s /var/run/fcgiwrap.socket -M 0666 -U nginx -- /usr/bin/fcgiwrap
