#!/bin/sh
#
# 50-gitweb-generate-conf
#
# generate gitweb.conf by using envsubst
#
envsubst '$PROJECTROOT$PROJECTS_LIST$DOCKER_HIGHLIGHT_CMT$GITWEB_BASEURL$GITWEB_SITE_NAME' < \
	$DOCKER_ENVSUBST_DIR/gitweb.conf.envsubst > /etc/gitweb.conf
